export const ADMIN_ACTUALITES_REQUEST = 'ADMIN_ACTUALITES_REQUEST';
export const ADMIN_ACTUALITES_SUCCESS = 'ADMIN_ACTUALITES_SUCCESS';
export const ADMIN_ACTUALITES_FAIL = 'ADMIN_ACTUALITES_FAIL';

export const ALL_ACTUALITES_REQUEST = 'ALL_ACTUALITES_REQUEST';
export const ALL_ACTUALITES_SUCCESS = 'ALL_ACTUALITES_SUCCESS';
export const ALL_ACTUALITES_FAIL = 'ALL_ACTUALITES_FAIL';

export const ACTUALITE_DETAILS_REQUEST = 'ACTUALITE_DETAILS_REQUEST';
export const ACTUALITE_DETAILS_SUCCESS = 'ACTUALITE_DETAILS_SUCCESS';
export const ACTUALITE_DETAILS_FAIL = 'ACTUALITE_DETAILS_FAIL';

export const NEW_ACTUALITE_REQUEST = 'NEW_ACTUALITE_REQUEST';
export const NEW_ACTUALITE_SUCCESS = 'NEW_ACTUALITE_SUCCESS';
export const NEW_ACTUALITE_FAIL = 'NEW_ACTUALITE_FAIL';
export const NEW_ACTUALITE_RESET = 'NEW_ACTUALITE_RESET';

export const DELETE_ACTUALITE_REQUEST = 'DELETE_ACTUALITE_REQUEST';
export const DELETE_ACTUALITE_SUCCESS = 'DELETE_ACTUALITE_SUCCESS';
export const DELETE_ACTUALITE_FAIL = 'DELETE_ACTUALITE_FAIL';
export const DELETE_ACTUALITE_RESET = 'DELETE_ACTUALITE_RESET';

export const UPDATE_ACTUALITE_REQUEST = 'UPDATE_ACTUALITE_REQUEST';
export const UPDATE_ACTUALITE_SUCCESS = 'UPDATE_ACTUALITE_SUCCESS';
export const UPDATE_ACTUALITE_FAIL = 'UPDATE_ACTUALITE_FAIL';
export const UPDATE_ACTUALITE_RESET = 'UPDATE_ACTUALITE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';